version: '3.9'
volumes:
  postgres_data:
  public_data:
  tmp_data:
  log_data:
services:
  app: &app_base
    build:
      context: .
      dockerfile: ./Docker/app/Dockerfile
    command: bundle exec puma -C config/puma.rb
    
    volumes:
      - .:/voice-cloud
      - public_data:/voice-cloud/public
      - tmp_data:/voice-cloud/tmp
      - log_data:/voice-cloud/log
    depends_on:
      - db
  webpack:
    <<: *app_base
    command: bash -c "rm -rf /app/public/packs; bin/webpack-dev-server"
    ports:
      - "3035:3035"
    depends_on:
      - app
    tty: false
    stdin_open: false
  db:
    build:
        context: .
        dockerfile: ./Docker/db/Dockerfile
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: ./Docker/web/Dockerfile
    volumes:
      - public_data:/voice-cloud/public
      - tmp_data:/voice-cloud/tmp
    ports:
      - 80:80
    depends_on:
      - app
  chrome:
    image: selenium/standalone-chrome:latest
    logging:
      driver: none
  smtp: 
    image: schickling/mailcatcher
    ports: 
      - '1080:1080'
      - '1025:1025'