version: '3.2'

volumes:
  dbdata:
    driver: local

services:
  db:
    image: postgres:11
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - dbdata:/var/lib/postgresql/data/pgdata

  web:
    build: .
    ports:
      - '3000:3000'
    # command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    command: bash -c "bundle exec puma && /usr/sbin/nginx -g 'daemon off;' -c /etc/nginx/nginx.conf"
    environment:
      RAILS_ENV: development
      RACK_ENV: development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      WEBPACKER_DEV_SERVER_HOST: webpack
    volumes:
      - .:/usr/src/voice-cloud
    depends_on:
      - db
      - webpack
  webpack:
    build: .
    command: ./bin/webpack-dev-server
    volumes:
      - .:/usr/src/voice-cloud
    ports:
      - '3035:3035'
    environment:
      NODE_ENV: development
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0