version: '3.7'

volumes:
  public-data:
  tmp-data:
  log-data:
  dbdata:
    driver: local

services:
  db:
    image: postgres:11
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - dbdata:/var/lib/postgresql/data/pgdata

  app:
    build: 
      context: .
    command: bundle exec puma -C config/puma.rb
    environment:
      RAILS_ENV: development
      RACK_ENV: development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - .:/voice_cloud
      - public-data:/voice_cloud/public
      - tmp-data:/voice_cloud/tmp
      - log-data:/voice_cloud/log
    depends_on:
      - db
      - webpack
  web: 
    build: 
      context: containers/nginx
    volumes: 
      - .:/voice_cloud
      - public-data:/voice_cloud/public 
      - tmp-data:/voice_cloud/tmp
    ports:
      - 80:80
    depends_on:
      - app
      - webpack
    environment: 
      WEBPACKER_DEV_SERVER_HOST: webpack

  webpack:
    build: .
    command: ./bin/webpack-dev-server
    volumes:
      - .:/voice_cloud
    ports:
      - '3035:3035'
    environment:
      NODE_ENV: development
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0