default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: voicecloud_development

test:
  <<: *default
  database: voicecloud_test

production: 
  <<: *default
  database: voicecloud_production
  username: postgres
  password: password